# docker-compose.yml para IzpoChat Backend
version: '3.8'

services:
  # Aplicación principal
  app:
    build: .
    container_name: izpochat-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - APP_NAME=${APP_NAME:-IzpoChat API}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs
      - ${GOOGLE_APPLICATION_CREDENTIALS}:${GOOGLE_APPLICATION_CREDENTIALS}:ro
    networks:
      - izpochat-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis para cache y sesiones (opcional)
  redis:
    image: redis:7-alpine
    container_name: izpochat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - izpochat-network
    command: redis-server --appendonly yes

  # Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: izpochat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - izpochat-network
    depends_on:
      - app

volumes:
  redis_data:

networks:
  izpochat-network:
    driver: bridge